baseURL = 'https://yano-san.com/'
languageCode = 'en-us'
title = 'yorinasub17'
theme = 'yanosan-solarized-theme-hugo'
paginate = 8

[params]
  github = 'https://github.com/yorinasub17'
  linkedin = 'https://www.linkedin.com/pub/yoriyasu-yano/1b/72/903/'

[markup.goldmark.renderer]
  unsafe = true
