baseURL = 'https://yano-san.com/'
languageCode = 'en-us'
title = 'yorinasub17'
theme = 'yanosan-solarized-theme-hugo'
paginate = 8

[params]
  github = 'https://github.com/yorinasub17'
  linkedin = 'https://www.linkedin.com/in/yoriyasu-yori-yano-9030721b/'
  wellfound = 'https://wellfound.com/u/yoriyasu-yano'

[markup.goldmark.renderer]
  unsafe = true
